# G:/My Drive/All24/gradle/libs.versions.toml
[versions]
activityCompose = "1.12.0-alpha04"
agp = "8.12.0-rc01" # Android Gradle Plugin version. You can check latest stable on Google's Maven.
composeBomVersion = "2025.07.00"
coreKtx = "1.17.0-beta01"
espressoCore = "3.7.0-rc01"
firebaseAuthKtx = "24.0.0"
firebaseBom = "34.0.0"
gson = "2.13.1"
junit = "4.13.2"
junitVersion = "1.3.0-rc01"
kotlin = "2.2.0"
googleServices = "4.4.3"
lifecycleRuntimeKtx = "2.9.2"
maps-compose = "6.12.0" # All24 - Add Maps Compose SDK
material = "1.12.0"
material3 = "1.4.0-alpha18"
navigationRuntimeAndroid = "2.9.2"
quarks = "1.0.0-alpha02"
uiTestJunit4 = "1.9.0-beta03"
firebaseMlCommon = "22.1.2"
uiGraphics = "1.8.3" # <--- ADD THIS LINE
parabolic-motion-animation = "v1.2"
recyclerview = "1.4.0"



[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version = "2.9.2" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "uiTestJunit4" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestJunit4" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTestJunit4" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiTestJunit4" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
engage-core = { group = "com.google.android.engage", name = "engage-core", version = "1.5.8" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version = "23.0.0" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version = "26.0.0" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
firebase-ml-common = { group = "com.google.firebase", name = "firebase-ml-common", version.ref = "firebaseMlCommon" }
google-api-client-android = { group = "com.google.api-client", name = "google-api-client-android", version = "2.8.0" }
google-sheets-api = { group = "com.google.apis", name = "google-api-services-sheets", version = "v4-rev20250616-2.0.0" }
google-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version = "21.4.0" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationRuntimeAndroid" }
maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "maps-compose" }
material = { module = "com.google.android.material:material", version.ref = "material" }
materialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
quarks = { module = "me.nikhilchaudhari:quarks", version.ref = "quarks" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" } # Add this line
parabolic-motion-animation = { group = "com.github.prathamesh-sonpatki", name = "Parabolic-Motion-Animation-in-Jetpack-Compose", version.ref = "parabolic-motion-animation" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
