# G:/My Drive/All24/gradle/libs.versions.toml
[versions]
activityCompose = "1.9.0"
room = "2.6.1"
agp = "8.5.0"
coil = "2.6.0"
composeBomVersion = "2024.06.00"
coreKtx = "1.13.1"
espressoCore = "3.5.1"
firebaseAuthKtx = "23.0.0"
firebaseBom = "33.1.1"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.24"
googleServices = "4.4.2"
lifecycleRuntimeKtx = "2.8.2"
maps-compose = "4.4.1"
material = "1.12.0"
material3 = "1.2.1"
navigationCompose = "2.7.7"
uiTestJunit4 = "1.6.8"
uiGraphics = "1.6.8"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "uiTestJunit4" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestJunit4" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTestJunit4" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiTestJunit4" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
google-api-client-android = { group = "com.google.api-client", name = "google-api-client-android", version = "2.4.0" }
google-sheets-api = { group = "com.google.apis", name = "google-api-services-sheets", version = "v4-rev20230815-2.0.0" }
google-play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version = "21.2.0" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "maps-compose" }
material = { module = "com.google.android.material:material", version.ref = "material" }
materialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
